// Generated by scripts/build-item-lore-signals.mjs. Do not edit by hand.

export type ItemLoreDescriptionSignal = {
  itemName: string;
  entryIds: string[];
  reason: string;
  confidence: 'canon' | 'inferred' | 'theory';
  source: 'description';
  evidence: string;
  matchedTerms: string[];
};

export const ITEM_LORE_DESCRIPTION_SIGNALS = [
  {
    "itemName": "Oceanic Essence",
    "entryIds": [
      "bestiary-sirens"
    ],
    "reason": "The item description explicitly references the Siren bestiary thread.",
    "confidence": "canon",
    "source": "description",
    "evidence": "A vial containing a shimmering, azure liquid extracted from the defeated Siren.",
    "matchedTerms": [
      "siren",
      "sirens"
    ]
  },
  {
    "itemName": "Siren's Scales",
    "entryIds": [
      "bestiary-sirens"
    ],
    "reason": "The item description explicitly references the Siren bestiary thread.",
    "confidence": "canon",
    "source": "description",
    "evidence": "A shimmering and iridescent scale obtained from the defeated Siren.",
    "matchedTerms": [
      "siren",
      "sirens"
    ]
  },
  {
    "itemName": "Siren's Soulstone",
    "entryIds": [
      "bestiary-sirens"
    ],
    "reason": "The item description explicitly references the Siren bestiary thread.",
    "confidence": "canon",
    "source": "description",
    "evidence": "A crystalline teardrop formed from the essence of a defeated Siren.",
    "matchedTerms": [
      "siren",
      "sirens"
    ]
  },
  {
    "itemName": "Aegis of the Seraph",
    "entryIds": [
      "concepts-gods-and-deities"
    ],
    "reason": "The item description uses divine or deity language connected to the Gods and Deities concept record.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "A radiant shield blessed by celestial beings, it deflects both physical and magical attacks.",
    "matchedTerms": [
      "celestial beings",
      "celestial deity",
      "forgotten god",
      "divine",
      "deity"
    ]
  },
  {
    "itemName": "Balthazar's Head",
    "entryIds": [
      "concepts-gods-and-deities"
    ],
    "reason": "The item description uses divine or deity language connected to the Gods and Deities concept record.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "The head of a dead celestial deity.",
    "matchedTerms": [
      "celestial beings",
      "celestial deity",
      "forgotten god",
      "divine",
      "deity"
    ]
  },
  {
    "itemName": "Celestial Crown",
    "entryIds": [
      "concepts-gods-and-deities"
    ],
    "reason": "The item description uses divine or deity language connected to the Gods and Deities concept record.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "A regal crown infused with celestial energy, it enhances the wearer's magical abilities and grants divine protection.",
    "matchedTerms": [
      "celestial beings",
      "celestial deity",
      "forgotten god",
      "divine",
      "deity"
    ]
  },
  {
    "itemName": "Dirella's Protection",
    "entryIds": [
      "concepts-gods-and-deities"
    ],
    "reason": "The item description uses divine or deity language connected to the Gods and Deities concept record.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "These mythic greaves are said to be once owned by a long-forgotten god.",
    "matchedTerms": [
      "celestial beings",
      "celestial deity",
      "forgotten god",
      "divine",
      "deity"
    ]
  },
  {
    "itemName": "Djinn's Bottle",
    "entryIds": [
      "artifacts-the-runemark-of-eternity",
      "world-the-citadel"
    ],
    "reason": "The item description uses rune language that aligns with the Runemark and Citadel archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "An ornately decorated bottle, sealed with mystic runes, faintly humming.",
    "matchedTerms": [
      "ancient runes",
      "runemark",
      "rune"
    ]
  },
  {
    "itemName": "Flameguard Plate",
    "entryIds": [
      "artifacts-the-runemark-of-eternity",
      "world-the-citadel"
    ],
    "reason": "The item description uses rune language that aligns with the Runemark and Citadel archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "This chestplate is inscribed with fiery runes, reducing the impact of flames and granting resistance to heat-based attacks.",
    "matchedTerms": [
      "ancient runes",
      "runemark",
      "rune"
    ]
  },
  {
    "itemName": "Forbidden Tome",
    "entryIds": [
      "artifacts-the-runemark-of-eternity",
      "world-the-citadel"
    ],
    "reason": "The item description uses rune language that aligns with the Runemark and Citadel archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "A dark, ancient book bound in strange leather, with cryptic, glowing runes on its cover.",
    "matchedTerms": [
      "ancient runes",
      "runemark",
      "rune"
    ]
  },
  {
    "itemName": "Grasps of Protection",
    "entryIds": [
      "artifacts-the-runemark-of-eternity",
      "world-the-citadel"
    ],
    "reason": "The item description uses rune language that aligns with the Runemark and Citadel archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "Inscribed with ancient runes, these gauntlets enhance magical abilities and offer protection against mystical forces.",
    "matchedTerms": [
      "ancient runes",
      "runemark",
      "rune"
    ]
  },
  {
    "itemName": "Runeblade Dagger",
    "entryIds": [
      "artifacts-the-runemark-of-eternity",
      "world-the-citadel"
    ],
    "reason": "The item description uses rune language that aligns with the Runemark and Citadel archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "Adorned with ancient runes, this dagger channels mystical powers to amplify its cutting edge.",
    "matchedTerms": [
      "ancient runes",
      "runemark",
      "rune"
    ]
  },
  {
    "itemName": "Runeblade Dagger Recipe",
    "entryIds": [
      "artifacts-the-runemark-of-eternity",
      "world-the-citadel"
    ],
    "reason": "The item description uses rune language that aligns with the Runemark and Citadel archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "Used to forge a legendary Runeblade (Dagger)",
    "matchedTerms": [
      "ancient runes",
      "runemark",
      "rune"
    ]
  },
  {
    "itemName": "Runeblade Sword",
    "entryIds": [
      "artifacts-the-runemark-of-eternity",
      "world-the-citadel"
    ],
    "reason": "The item description uses rune language that aligns with the Runemark and Citadel archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "Inscribed with ancient runes, this sword channels mystic energies to enhance its strikes.",
    "matchedTerms": [
      "ancient runes",
      "runemark",
      "rune"
    ]
  },
  {
    "itemName": "Runeblade Sword Recipe",
    "entryIds": [
      "artifacts-the-runemark-of-eternity",
      "world-the-citadel"
    ],
    "reason": "The item description uses rune language that aligns with the Runemark and Citadel archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "Used to forge a mythic Runeblade (Sword)",
    "matchedTerms": [
      "ancient runes",
      "runemark",
      "rune"
    ]
  },
  {
    "itemName": "Runebound Bulwark",
    "entryIds": [
      "artifacts-the-runemark-of-eternity",
      "world-the-citadel"
    ],
    "reason": "The item description uses rune language that aligns with the Runemark and Citadel archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "Inscribed with ancient runes, this shield enhances the bearer's magical abilities and grants protection against enchantments.",
    "matchedTerms": [
      "ancient runes",
      "runemark",
      "rune"
    ]
  },
  {
    "itemName": "Runebound Bulwark Recipe",
    "entryIds": [
      "artifacts-the-runemark-of-eternity",
      "world-the-citadel"
    ],
    "reason": "The item description uses rune language that aligns with the Runemark and Citadel archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "Used to forge a legendary Runebound Bulwark (Shield)",
    "matchedTerms": [
      "ancient runes",
      "runemark",
      "rune"
    ]
  },
  {
    "itemName": "Runebound Footwraps",
    "entryIds": [
      "artifacts-the-runemark-of-eternity",
      "world-the-citadel"
    ],
    "reason": "The item description uses rune language that aligns with the Runemark and Citadel archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "Inscribed with ancient runes, these boots enhance the wearer's magical abilities and provide extra protection against spells.",
    "matchedTerms": [
      "ancient runes",
      "runemark",
      "rune"
    ]
  },
  {
    "itemName": "Runebound Footwraps Recipe",
    "entryIds": [
      "artifacts-the-runemark-of-eternity",
      "world-the-citadel"
    ],
    "reason": "The item description uses rune language that aligns with the Runemark and Citadel archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "Used to forge a legendary Runebound Footwraps (Boots)",
    "matchedTerms": [
      "ancient runes",
      "runemark",
      "rune"
    ]
  },
  {
    "itemName": "Runebound Helm",
    "entryIds": [
      "artifacts-the-runemark-of-eternity",
      "world-the-citadel"
    ],
    "reason": "The item description uses rune language that aligns with the Runemark and Citadel archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "Inscribed with ancient runes, this helm enhances the wearer's magical potential and provides protection against hostile enchantments.",
    "matchedTerms": [
      "ancient runes",
      "runemark",
      "rune"
    ]
  },
  {
    "itemName": "Runebound Helm Recipe",
    "entryIds": [
      "artifacts-the-runemark-of-eternity",
      "world-the-citadel"
    ],
    "reason": "The item description uses rune language that aligns with the Runemark and Citadel archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "Used to forge a legendary Runebound Helm (Helmet)",
    "matchedTerms": [
      "ancient runes",
      "runemark",
      "rune"
    ]
  },
  {
    "itemName": "Runebound Shinplates",
    "entryIds": [
      "artifacts-the-runemark-of-eternity",
      "world-the-citadel"
    ],
    "reason": "The item description uses rune language that aligns with the Runemark and Citadel archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "Inscribed with ancient runes, these greaves provide enhanced magical defense and amplify the wearer's spellcasting abilities.",
    "matchedTerms": [
      "ancient runes",
      "runemark",
      "rune"
    ]
  },
  {
    "itemName": "Runebound Shinplates Recipe",
    "entryIds": [
      "artifacts-the-runemark-of-eternity",
      "world-the-citadel"
    ],
    "reason": "The item description uses rune language that aligns with the Runemark and Citadel archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "Used to forge a legendary Runebound Shinplates (Greaves)",
    "matchedTerms": [
      "ancient runes",
      "runemark",
      "rune"
    ]
  },
  {
    "itemName": "Sentinel's Bulwark",
    "entryIds": [
      "civilizations-the-ancients",
      "civilizations-the-first-people"
    ],
    "reason": "The item description points at the oldest civilization layer in the lore archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "Carrying the spirit of ancient guardians, this shield provides exceptional defense and inspires courage in allies.",
    "matchedTerms": [
      "the ancients",
      "ancient civilization",
      "first people"
    ]
  },
  {
    "itemName": "Sentinel's Embrace",
    "entryIds": [
      "civilizations-the-ancients",
      "civilizations-the-first-people"
    ],
    "reason": "The item description points at the oldest civilization layer in the lore archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "This chestplate carries the essence of ancient guardians, providing unparalleled defense against physical blows.",
    "matchedTerms": [
      "the ancients",
      "ancient civilization",
      "first people"
    ]
  },
  {
    "itemName": "Sentinel's Gauntlets",
    "entryIds": [
      "civilizations-the-ancients",
      "civilizations-the-first-people"
    ],
    "reason": "The item description points at the oldest civilization layer in the lore archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "Forged by ancient guardians, these gauntlets provide exceptional defense and augment the wearer's reflexes.",
    "matchedTerms": [
      "the ancients",
      "ancient civilization",
      "first people"
    ]
  },
  {
    "itemName": "Sentinel's Gaze",
    "entryIds": [
      "civilizations-the-ancients",
      "civilizations-the-first-people"
    ],
    "reason": "The item description points at the oldest civilization layer in the lore archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "Imbued with the sight of ancient guardians, this helm grants the wearer heightened perception and resistance to illusions.",
    "matchedTerms": [
      "the ancients",
      "ancient civilization",
      "first people"
    ]
  },
  {
    "itemName": "Sentinel's Resolve",
    "entryIds": [
      "civilizations-the-ancients",
      "civilizations-the-first-people"
    ],
    "reason": "The item description points at the oldest civilization layer in the lore archive.",
    "confidence": "inferred",
    "source": "description",
    "evidence": "Greaves imbued with the unwavering determination of ancient guardians, granting enhanced stamina and resistance to fatigue.",
    "matchedTerms": [
      "the ancients",
      "ancient civilization",
      "first people"
    ]
  },
  {
    "itemName": "Ancient Parchment",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2025 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Ancient Parchment (2024)",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2024 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Bloodmoon Bow",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Aligned with the lunar eclipse, this bow fires arrows that pulse with an insatiable thirst for blood.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Celestial Scroll",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2025 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Celestial Scroll (2024)",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2024 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Cursed Ticket (2024)",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2024 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Ethereal Gem",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2025 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Ethereal Gem (2024)",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2024 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Lunar Radiance",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "A helm infused with lunar energy, it enhances the wearer's perception under moonlight and grants moon-based abilities.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Lunar Radiance Recipe",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Used to forge a legendary Lunar Radiance (Helmet)",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Lunar Stone",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2025 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Lunar Stone (2024)",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2024 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Lunar Ticket",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2025 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Lunar Ticket (2024)",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2024 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Lunar Ticket (Untradable)",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2025 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Lunarweave Boots",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Woven with lunar threads, these boots enhance the wearer's balance and agility under the moon's glow.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Lunarweave Gloves",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Woven with lunar threads, these gauntlets grant enhanced agility and heightened senses during nighttime.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Lunarweave Leggings",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Woven with lunar threads, these greaves enhance the wearer's balance and agility under moonlit conditions.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Moonblood Tincture",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "A small vial containing a potent elixir derived from rare moonbloom flowers, known for their connection to the lunar energies.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Moonlance",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Forged from moonlight itself, this dagger harnesses lunar energy to pierce through defenses.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Moonlight Essence",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2025 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Moonlight Essence (2024)",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2024 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Moonlit Chalice",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2025 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Moonlit Chalice (2024)",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2024 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Moonshadow",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "A dagger imbued with lunar energy, it glows softly in the darkness, enhancing its wielder's senses.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Moonshadow Guard",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Woven with moonlit threads, this shield enhances agility and offers heightened protection during nighttime.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Moonshadow Vestment",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Woven from moonlit threads, this chestplate grants its wearer enhanced agility and the ability to move effortlessly in darkness.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Moonshot",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Drawing power from the lunar cycles, this bow launches arrows that glow with moonlit radiance.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Moonstone Ink",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2025 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Moonstone Ink (2024)",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2024 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Piercer",
    "entryIds": [
      "concepts-colossal-serpent"
    ],
    "reason": "The item description uses reality/void language; this is a cosmology research hook, not a confirmed link.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Forged in the depths of the void, this bow shoots arrows that tear through dimensional barriers.",
    "matchedTerms": [
      "void",
      "reality",
      "phaseshift"
    ]
  },
  {
    "itemName": "Serpent Scale Recipe",
    "entryIds": [
      "concepts-colossal-serpent"
    ],
    "reason": "The item description uses serpent imagery; this is a thematic hook, not proof of identity.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Used to forge a legendary Serpent Scale Armor (Chestplate)",
    "matchedTerms": [
      "serpent",
      "colossal serpent"
    ]
  },
  {
    "itemName": "Serpent's Arrow",
    "entryIds": [
      "concepts-colossal-serpent"
    ],
    "reason": "The item description uses serpent imagery; this is a thematic hook, not proof of identity.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This bow is adorned with serpent motifs, and its arrows possess a venomous bite that weakens foes.",
    "matchedTerms": [
      "serpent",
      "colossal serpent"
    ]
  },
  {
    "itemName": "Serpent's Arrow Recipe",
    "entryIds": [
      "concepts-colossal-serpent"
    ],
    "reason": "The item description uses serpent imagery; this is a thematic hook, not proof of identity.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Used to forge a legendary Serpent's Arrow (Bow)",
    "matchedTerms": [
      "serpent",
      "colossal serpent"
    ]
  },
  {
    "itemName": "Serpent's Kiss",
    "entryIds": [
      "concepts-colossal-serpent"
    ],
    "reason": "The item description uses serpent imagery; this is a thematic hook, not proof of identity.",
    "confidence": "theory",
    "source": "description",
    "evidence": "The blade of this dagger curls like a serpent, delivering a venomous strike that weakens the victim.",
    "matchedTerms": [
      "serpent",
      "colossal serpent"
    ]
  },
  {
    "itemName": "Serpent's Kiss Recipe",
    "entryIds": [
      "concepts-colossal-serpent"
    ],
    "reason": "The item description uses serpent imagery; this is a thematic hook, not proof of identity.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Used to forge a legendary Serpent's Kiss (Dagger)",
    "matchedTerms": [
      "serpent",
      "colossal serpent"
    ]
  },
  {
    "itemName": "Serpentstrike",
    "entryIds": [
      "concepts-colossal-serpent"
    ],
    "reason": "The item description uses serpent imagery; this is a thematic hook, not proof of identity.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Swift and deadly, this sword strikes with the venomous precision of a serpent.",
    "matchedTerms": [
      "serpent",
      "colossal serpent"
    ]
  },
  {
    "itemName": "Snakes Head",
    "entryIds": [
      "concepts-colossal-serpent"
    ],
    "reason": "The item description uses serpent imagery; this is a thematic hook, not proof of identity.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Severed head of a serpent, fangs bared, with hypnotic, still-glowing eyes.",
    "matchedTerms": [
      "serpent",
      "colossal serpent"
    ]
  },
  {
    "itemName": "Starfire Plate",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Gleaming with celestial energy, this chestplate absorbs and channels the power of stars, granting magical protection.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Starglitter",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This dagger captures the essence of the stars, its blade twinkling with cosmic radiance.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Starlight Gem",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2025 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Starlight Gem (2024)",
    "entryIds": [
      "world-the-celestial-system-of-valaron",
      "concepts-cults"
    ],
    "reason": "The item description uses sky, lunar, or star language that can support celestial-system research.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This item can only be used in the Moonlit Festival 2024 campaign.",
    "matchedTerms": [
      "celestial system",
      "lunar",
      "stars"
    ]
  },
  {
    "itemName": "Voidrend Gauntlets",
    "entryIds": [
      "concepts-colossal-serpent"
    ],
    "reason": "The item description uses reality/void language; this is a cosmology research hook, not a confirmed link.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Forged from the void itself, these gauntlets can tear through the fabric of reality, allowing the wearer to phase through obstacles.",
    "matchedTerms": [
      "void",
      "reality",
      "phaseshift"
    ]
  },
  {
    "itemName": "Voidslayer",
    "entryIds": [
      "concepts-colossal-serpent"
    ],
    "reason": "The item description uses reality/void language; this is a cosmology research hook, not a confirmed link.",
    "confidence": "theory",
    "source": "description",
    "evidence": "This sword has the power to cleave through the fabric of reality itself, cutting through the void.",
    "matchedTerms": [
      "void",
      "reality",
      "phaseshift"
    ]
  },
  {
    "itemName": "Voidstep Boots",
    "entryIds": [
      "concepts-colossal-serpent"
    ],
    "reason": "The item description uses reality/void language; this is a cosmology research hook, not a confirmed link.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Woven with threads from the void, these boots allow the wearer to briefly step into the ethereal plane, passing through obstacles.",
    "matchedTerms": [
      "void",
      "reality",
      "phaseshift"
    ]
  },
  {
    "itemName": "Voidwalker Cowl",
    "entryIds": [
      "concepts-colossal-serpent"
    ],
    "reason": "The item description uses reality/void language; this is a cosmology research hook, not a confirmed link.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Woven with threads from the void, this cowl grants the wearer limited phaseshift abilities, allowing them to temporarily fade from reality.",
    "matchedTerms": [
      "void",
      "reality",
      "phaseshift"
    ]
  },
  {
    "itemName": "Voidwalker Striders",
    "entryIds": [
      "concepts-colossal-serpent"
    ],
    "reason": "The item description uses reality/void language; this is a cosmology research hook, not a confirmed link.",
    "confidence": "theory",
    "source": "description",
    "evidence": "Forged from the void itself, these greaves allow the wearer to phase through solid objects and briefly enter the ethereal plane.",
    "matchedTerms": [
      "void",
      "reality",
      "phaseshift"
    ]
  }
] as const satisfies readonly ItemLoreDescriptionSignal[];
